export const CHANGE_MAP_SIZE = "CHANGE_MAP_SIZE";
export const ADD_PLAYER = "ADD_PLAYER";
export const CHANGE_PLAYER_ICON = "CHANGE_PLAYER_ICON"; 
export const CHANGE_PLAYER_NAME = "CHANGE_PLAYER_NAME";
export const REMOVE_PLAYER = "REMOVE_PLAYER";